import React from "react";
import { Button } from "@/components/ui/button";
import type { SceneSummary } from "@/features/scene-lab/types";

export function SceneLibrary({ scenes, generating, onGenerate, onOpen }: { scenes: SceneSummary[]; generating: boolean; onGenerate: () => void; onOpen: (lessonId: number) => void }) {
  const kitchen = scenes.find((scene) => scene.scene_key === "kitchen");
  const progress = kitchen?.total ? Math.round(kitchen.learned / kitchen.total * 100) : 0;
  return <div className="mx-auto max-w-5xl p-8"><div className="mb-8"><p className="text-xs font-bold uppercase tracking-[.2em] text-primary">Spatial memory</p><h1 className="mt-2 font-serif text-4xl font-bold">场景学习</h1><p className="mt-2 max-w-2xl text-muted-foreground">在 3D 空间中学习单词、搭配和动作。位置会成为你的记忆线索。</p></div><div className="grid gap-4 md:grid-cols-3"><article className="overflow-hidden rounded-2xl border bg-card shadow-sm"><div className="h-40 bg-gradient-to-br from-amber-100 via-orange-100 to-teal-100 p-5"><span className="text-6xl">🍳</span></div><div className="p-5"><div className="flex items-start justify-between"><div><h2 className="font-serif text-2xl font-bold">Kitchen</h2><p className="text-sm text-muted-foreground">厨房 · 20 个互动对象</p></div><span className="rounded-full bg-primary/10 px-2 py-1 text-xs font-bold text-primary">{progress}%</span></div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full bg-primary" style={{ width: `${progress}%` }} /></div><Button onClick={() => kitchen?.lesson_id ? onOpen(kitchen.lesson_id) : onGenerate()} disabled={generating} className="mt-5 w-full">{generating ? "AI 正在生成课程…" : kitchen?.lesson_id ? "继续学习" : "生成 Kitchen 课程"}</Button></div></article>{["Airport", "Office"].map((name) => <article key={name} className="rounded-2xl border border-dashed bg-muted/20 p-5 opacity-60"><div className="flex h-40 items-center justify-center text-4xl">{name === "Airport" ? "✈️" : "💼"}</div><h2 className="font-serif text-xl font-bold">{name}</h2><p className="mt-1 text-sm text-muted-foreground">Coming Soon</p></article>)}</div></div>;
}
