import type { Dict } from "../types";

export const writing: Dict = {
  "writing.title": "Writing Studio", "writing.subtitle": "Write more naturally, and understand why.", "writing.aiReady": "AI ready",
  "writing.compose": "Start writing", "writing.records": "Writing records", "writing.summaries": "Learning summaries", "writing.library": "Manuscripts",
  "writing.quick": "Quick refine", "writing.deep": "Deep analysis", "writing.quickHint": "Polish quickly with a few key suggestions", "writing.deepHint": "Analyze expression, structure, logic, and tone",
  "writing.yourWriting": "Your writing", "writing.inputHint": "Enter a sentence, paragraph, or full essay", "writing.placeholder": "Start writing in English…", "writing.words": "{count} words",
  "writing.modelEssay": "Reference essay", "writing.essayCount": "{count}", "writing.stop": "Stop", "writing.analyze": "Analyze", "writing.analyzeAgain": "Analyze again", "writing.analyzing": "Analyzing…",
  "writing.result": "AI feedback", "writing.emptyTitle": "Your feedback appears here", "writing.emptyHint": "You decide which sentences and words are worth saving.", "writing.progress": "Analyzing · {count} characters",
  "writing.refined": "Refined version", "writing.analysis": "Analysis", "writing.candidates": "Expressions worth saving", "writing.vocabulary": "Suggested vocabulary", "writing.modelEssays": "Reference essays",
  "writing.original": "Original", "writing.refinedSnippet": "Refined", "writing.explanation": "Note", "writing.collect": "Save sentence", "writing.collected": "Saved",
  "writing.collectAll": "Save all", "writing.collectedAll": "All saved", "writing.savedAll": "Saved to writing records",
  "writing.addCustomSentence": "Add your own sentence", "writing.originalSentence": "Original sentence", "writing.refinedSentence": "Refined sentence",
  "writing.addVocab": "Add to vocabulary", "writing.vocabAdded": "Added", "writing.alreadyExists": "“{word}” is already in Vocabulary", "writing.addCustomVocab": "Add your own word",
  "writing.word": "Word or expression", "writing.meaning": "Meaning", "writing.example": "Example in context", "writing.reason": "Note or reason", "writing.add": "Add", "writing.cancel": "Cancel", "writing.searchVocab": "Search or enter a word…",
  "writing.savedSentence": "Sentence saved", "writing.saveFailed": "Save failed: {error}", "writing.vocabSaved": "Added to Vocabulary", "writing.invalidCustomVocab": "Enter a word or expression",
  "writing.search": "Search writing records…", "writing.summarizing": "Summarizing…", "writing.summarizeSelected": "Summarize selected {count}", "writing.delete": "Delete", "writing.noRecords": "No writing records yet",
  "writing.selectRecord": "Select a writing record", "writing.selectRecordHint": "Review the original and refined expressions you chose to save.", "writing.items": "{count} saved items", "writing.general": "Saved expression", "writing.overview": "Overview",
  "writing.merging": "Merging…", "writing.mergeSelected": "Merge selected {count}", "writing.noSummaries": "No learning summaries yet", "writing.selectSummary": "Select a learning summary", "writing.selectSummaryHint": "Review your progress and generate an editable document.", "writing.exportDocument": "Generate document",
  "writing.summarySaved": "Summary saved", "writing.summaryTitle": "Writing summary · {date}", "writing.deleteSourceTitle": "Delete summary sources?", "writing.deleteRecordsTitle": "Delete writing content?", "writing.deleteSummariesTitle": "Delete learning summaries?", "writing.deleteSourceConfirm": "Permanently delete the {records} records and {sentences} saved sentences used for this summary? Vocabulary entries will remain.", "writing.deleteRecordsConfirm": "Permanently delete {records} records and {sentences} saved sentences? Vocabulary entries will remain.", "writing.deleteSummariesConfirm": "Permanently delete {count} learning summaries?",
  "writing.exportTitle": "Generate document", "writing.titleLabel": "Title", "writing.destination": "Save to", "writing.database": "TanWords database", "writing.databaseHint": "Save in Documents and continue editing", "writing.localFolder": "Local folder", "writing.noFolder": "No folder selected", "writing.chooseFolder": "Choose folder", "writing.chooseSaveFolder": "Choose save folder", "writing.saving": "Saving…", "writing.confirmSave": "Save", "writing.generatedDocument": "Database document created", "writing.openDocuments": "Open Documents", "writing.savedTo": "Saved to {path}", "writing.exportFailed": "Could not generate document: {error}", "writing.generatedAt": "Generated {date}",
};
