//! GENERATED by scripts/gen_dispatch.py — do not edit by hand.
//! Regenerate after adding or changing a command.

use crate::rpc::{Args, Ctx};
use serde_json::Value;

pub async fn dispatch(ctx: &Ctx, command: &str, mut args: Args) -> Result<Value, String> {
    #[allow(unused_mut, unused_variables)]
    match command {
    "db_get_word_count" => {

        let out = db::settings::db_get_word_count(ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_get_translation_count" => {

        let out = db::settings::db_get_translation_count(ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_get_review_count" => {

        let out = db::srs::db_get_review_count(ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_get_words" => {
        let search = args.take("search").map_err(|e| format!("db_get_words: bad argument `search`: {e}"))?;
        let level_filter = args.take("level_filter").map_err(|e| format!("db_get_words: bad argument `level_filter`: {e}"))?;
        let sort_by = args.take("sort_by").map_err(|e| format!("db_get_words: bad argument `sort_by`: {e}"))?;
        let date_field = args.take("date_field").map_err(|e| format!("db_get_words: bad argument `date_field`: {e}"))?;
        let date_from = args.take("date_from").map_err(|e| format!("db_get_words: bad argument `date_from`: {e}"))?;
        let date_to = args.take("date_to").map_err(|e| format!("db_get_words: bad argument `date_to`: {e}"))?;
        let out = db::words_query::db_get_words(search, level_filter, sort_by, date_field, date_from, date_to, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_get_word_detail" => {
        let word_id = args.take("word_id").map_err(|e| format!("db_get_word_detail: bad argument `word_id`: {e}"))?;
        let out = db::words_query::db_get_word_detail(word_id, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_add_word" => {
        let word = args.take("word").map_err(|e| format!("db_add_word: bad argument `word`: {e}"))?;
        let word_type = args.take("word_type").map_err(|e| format!("db_add_word: bad argument `word_type`: {e}"))?;
        let level = args.take("level").map_err(|e| format!("db_add_word: bad argument `level`: {e}"))?;
        let zh = args.take("zh").map_err(|e| format!("db_add_word: bad argument `zh`: {e}"))?;
        let out = db::words_write::db_add_word(word, word_type, level, zh, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_delete_word" => {
        let word_id = args.take("word_id").map_err(|e| format!("db_delete_word: bad argument `word_id`: {e}"))?;
        let out = db::words_write::db_delete_word(word_id, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_delete_words_batch" => {
        let word_ids = args.take("word_ids").map_err(|e| format!("db_delete_words_batch: bad argument `word_ids`: {e}"))?;
        let out = db::words_write::db_delete_words_batch(word_ids, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_set_word_starred" => {
        let word_id = args.take("word_id").map_err(|e| format!("db_set_word_starred: bad argument `word_id`: {e}"))?;
        let starred = args.take("starred").map_err(|e| format!("db_set_word_starred: bad argument `starred`: {e}"))?;
        let out = db::words_write::db_set_word_starred(word_id, starred, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_get_setting" => {
        let key = args.take("key").map_err(|e| format!("db_get_setting: bad argument `key`: {e}"))?;
        let out = db::settings::db_get_setting(key, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_set_setting" => {
        let key = args.take("key").map_err(|e| format!("db_set_setting: bad argument `key`: {e}"))?;
        let value = args.take("value").map_err(|e| format!("db_set_setting: bad argument `value`: {e}"))?;
        let out = db::settings::db_set_setting(key, value, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_save_translation" => {
        let source_text = args.take("source_text").map_err(|e| format!("db_save_translation: bad argument `source_text`: {e}"))?;
        let result_text = args.take("result_text").map_err(|e| format!("db_save_translation: bad argument `result_text`: {e}"))?;
        let source_lang = args.take("source_lang").map_err(|e| format!("db_save_translation: bad argument `source_lang`: {e}"))?;
        let target_lang = args.take("target_lang").map_err(|e| format!("db_save_translation: bad argument `target_lang`: {e}"))?;
        let provider = args.take("provider").map_err(|e| format!("db_save_translation: bad argument `provider`: {e}"))?;
        let mode = args.take("mode").map_err(|e| format!("db_save_translation: bad argument `mode`: {e}"))?;
        let out = db::translations::db_save_translation(source_text, result_text, source_lang, target_lang, provider, mode, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_get_translations" => {
        let search = args.take("search").map_err(|e| format!("db_get_translations: bad argument `search`: {e}"))?;
        let cluster = args.take("cluster").map_err(|e| format!("db_get_translations: bad argument `cluster`: {e}"))?;
        let out = db::translations::db_get_translations(search, cluster, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_get_quiz_words" => {
        let limit = args.take("limit").map_err(|e| format!("db_get_quiz_words: bad argument `limit`: {e}"))?;
        let out = db::quiz::db_get_quiz_words(limit, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_save_quiz_result" => {
        let word_id = args.take("word_id").map_err(|e| format!("db_save_quiz_result: bad argument `word_id`: {e}"))?;
        let is_correct = args.take("is_correct").map_err(|e| format!("db_save_quiz_result: bad argument `is_correct`: {e}"))?;
        let out = db::quiz::db_save_quiz_result(word_id, is_correct, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_add_word_enriched" => {
        let word = args.take("word").map_err(|e| format!("db_add_word_enriched: bad argument `word`: {e}"))?;
        let zh = args.take("zh").map_err(|e| format!("db_add_word_enriched: bad argument `zh`: {e}"))?;
        let word_type = args.take("word_type").map_err(|e| format!("db_add_word_enriched: bad argument `word_type`: {e}"))?;
        let enrichment = args.take("enrichment").map_err(|e| format!("db_add_word_enriched: bad argument `enrichment`: {e}"))?;
        let out = db::words_write::db_add_word_enriched(word, zh, word_type, enrichment, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_get_word_extras" => {
        let word_id = args.take("word_id").map_err(|e| format!("db_get_word_extras: bad argument `word_id`: {e}"))?;
        let out = db::words_write::db_get_word_extras(word_id, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_save_word_notes" => {
        let word_id = args.take("word_id").map_err(|e| format!("db_save_word_notes: bad argument `word_id`: {e}"))?;
        let notes = args.take("notes").map_err(|e| format!("db_save_word_notes: bad argument `notes`: {e}"))?;
        let out = db::words_write::db_save_word_notes(word_id, notes, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_save_word_chat" => {
        let word_id = args.take("word_id").map_err(|e| format!("db_save_word_chat: bad argument `word_id`: {e}"))?;
        let messages = args.take("messages").map_err(|e| format!("db_save_word_chat: bad argument `messages`: {e}"))?;
        let out = db::words_write::db_save_word_chat(word_id, messages, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_create_document" => {

        let out = db::documents::crud::db_create_document(ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_create_document_with_content" => {
        let title = args.take("title").map_err(|e| format!("db_create_document_with_content: bad argument `title`: {e}"))?;
        let content = args.take("content").map_err(|e| format!("db_create_document_with_content: bad argument `content`: {e}"))?;
        let content_text = args.take("content_text").map_err(|e| format!("db_create_document_with_content: bad argument `content_text`: {e}"))?;
        let tags = args.take("tags").map_err(|e| format!("db_create_document_with_content: bad argument `tags`: {e}"))?;
        let word_count = args.take("word_count").map_err(|e| format!("db_create_document_with_content: bad argument `word_count`: {e}"))?;
        let out = db::documents::crud::db_create_document_with_content(title, content, content_text, tags, word_count, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_document_title_exists" => {
        let title = args.take("title").map_err(|e| format!("db_document_title_exists: bad argument `title`: {e}"))?;
        let out = db::documents::crud::db_document_title_exists(title, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_get_documents" => {
        let search = args.take("search").map_err(|e| format!("db_get_documents: bad argument `search`: {e}"))?;
        let date_from = args.take("date_from").map_err(|e| format!("db_get_documents: bad argument `date_from`: {e}"))?;
        let date_to = args.take("date_to").map_err(|e| format!("db_get_documents: bad argument `date_to`: {e}"))?;
        let tag = args.take("tag").map_err(|e| format!("db_get_documents: bad argument `tag`: {e}"))?;
        let sort = args.take("sort").map_err(|e| format!("db_get_documents: bad argument `sort`: {e}"))?;
        let page = args.take("page").map_err(|e| format!("db_get_documents: bad argument `page`: {e}"))?;
        let out = db::documents::crud::db_get_documents(search, date_from, date_to, tag, sort, page, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_get_document" => {
        let id = args.take("id").map_err(|e| format!("db_get_document: bad argument `id`: {e}"))?;
        let out = db::documents::crud::db_get_document(id, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_protect_document" => {
        let id = args.take("id").map_err(|e| format!("db_protect_document: bad argument `id`: {e}"))?;
        let password = args.take("password").map_err(|e| format!("db_protect_document: bad argument `password`: {e}"))?;
        let out = document_privacy::commands::db_protect_document(id, password, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_private_password_status" => {

        let out = document_privacy::commands::db_private_password_status(ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_unlock_document" => {
        let id = args.take("id").map_err(|e| format!("db_unlock_document: bad argument `id`: {e}"))?;
        let password = args.take("password").map_err(|e| format!("db_unlock_document: bad argument `password`: {e}"))?;
        let out = document_privacy::commands::db_unlock_document(id, password, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_lock_document" => {
        let _id = args.take("_id").map_err(|e| format!("db_lock_document: bad argument `_id`: {e}"))?;
        let out = document_privacy::commands::db_lock_document(_id, ctx.state::<AppState>())?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_remove_document_protection" => {
        let id = args.take("id").map_err(|e| format!("db_remove_document_protection: bad argument `id`: {e}"))?;
        let password = args.take("password").map_err(|e| format!("db_remove_document_protection: bad argument `password`: {e}"))?;
        let out = document_privacy::commands::db_remove_document_protection(id, password, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_change_document_password" => {
        let current_password = args.take("current_password").map_err(|e| format!("db_change_document_password: bad argument `current_password`: {e}"))?;
        let new_password = args.take("new_password").map_err(|e| format!("db_change_document_password: bad argument `new_password`: {e}"))?;
        let out = document_privacy::commands::db_change_document_password(current_password, new_password, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_create_document_asset" => {
        let document_id = args.take("document_id").map_err(|e| format!("db_create_document_asset: bad argument `document_id`: {e}"))?;
        let file_name = args.take("file_name").map_err(|e| format!("db_create_document_asset: bad argument `file_name`: {e}"))?;
        let mime_type = args.take("mime_type").map_err(|e| format!("db_create_document_asset: bad argument `mime_type`: {e}"))?;
        let data_base64 = args.take("data_base64").map_err(|e| format!("db_create_document_asset: bad argument `data_base64`: {e}"))?;
        let out = db::documents::assets_crud::db_create_document_asset(document_id, file_name, mime_type, data_base64, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_get_document_asset" => {
        let id = args.take("id").map_err(|e| format!("db_get_document_asset: bad argument `id`: {e}"))?;
        let out = db::documents::assets_crud::db_get_document_asset(id, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_get_document_assets" => {
        let document_id = args.take("document_id").map_err(|e| format!("db_get_document_assets: bad argument `document_id`: {e}"))?;
        let out = db::documents::assets_crud::db_get_document_assets(document_id, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_list_document_assets" => {

        let out = db::documents::assets_crud::db_list_document_assets(ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_delete_document_asset" => {
        let id = args.take("id").map_err(|e| format!("db_delete_document_asset: bad argument `id`: {e}"))?;
        let out = db::documents::assets_crud::db_delete_document_asset(id, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_delete_orphan_document_assets" => {

        let out = db::documents::assets_crud::db_delete_orphan_document_assets(ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_export_document_asset" => {
        let id = args.take("id").map_err(|e| format!("db_export_document_asset: bad argument `id`: {e}"))?;
        let destination = args.take("destination").map_err(|e| format!("db_export_document_asset: bad argument `destination`: {e}"))?;
        let out = db::documents::assets_export::db_export_document_asset(id, destination, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_export_document_assets_to_folder" => {
        let ids = args.take("ids").map_err(|e| format!("db_export_document_assets_to_folder: bad argument `ids`: {e}"))?;
        let destination = args.take("destination").map_err(|e| format!("db_export_document_assets_to_folder: bad argument `destination`: {e}"))?;
        let out = db::documents::assets_export::db_export_document_assets_to_folder(ids, destination, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_export_document_assets_zip" => {
        let ids = args.take("ids").map_err(|e| format!("db_export_document_assets_zip: bad argument `ids`: {e}"))?;
        let destination = args.take("destination").map_err(|e| format!("db_export_document_assets_zip: bad argument `destination`: {e}"))?;
        let out = db::documents::assets_export::db_export_document_assets_zip(ids, destination, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_get_document_link_context" => {
        let document_id = args.take("document_id").map_err(|e| format!("db_get_document_link_context: bad argument `document_id`: {e}"))?;
        let out = db::documents::links::db_get_document_link_context(document_id, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_prune_document_assets" => {
        let document_id = args.take("document_id").map_err(|e| format!("db_prune_document_assets: bad argument `document_id`: {e}"))?;
        let referenced_ids = args.take("referenced_ids").map_err(|e| format!("db_prune_document_assets: bad argument `referenced_ids`: {e}"))?;
        let out = db::documents::assets_crud::db_prune_document_assets(document_id, referenced_ids, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_update_document" => {
        let id = args.take("id").map_err(|e| format!("db_update_document: bad argument `id`: {e}"))?;
        let title = args.take("title").map_err(|e| format!("db_update_document: bad argument `title`: {e}"))?;
        let content = args.take("content").map_err(|e| format!("db_update_document: bad argument `content`: {e}"))?;
        let content_text = args.take("content_text").map_err(|e| format!("db_update_document: bad argument `content_text`: {e}"))?;
        let tags = args.take("tags").map_err(|e| format!("db_update_document: bad argument `tags`: {e}"))?;
        let pinned = args.take("pinned").map_err(|e| format!("db_update_document: bad argument `pinned`: {e}"))?;
        let word_count = args.take("word_count").map_err(|e| format!("db_update_document: bad argument `word_count`: {e}"))?;
        let out = db::documents::crud::db_update_document(id, title, content, content_text, tags, pinned, word_count, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_delete_document" => {
        let id = args.take("id").map_err(|e| format!("db_delete_document: bad argument `id`: {e}"))?;
        let out = db::documents::crud::db_delete_document(id, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_duplicate_document" => {
        let id = args.take("id").map_err(|e| format!("db_duplicate_document: bad argument `id`: {e}"))?;
        let out = db::documents::duplicate::db_duplicate_document(id, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_get_all_tags" => {

        let out = db::documents::crud::db_get_all_tags(ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_list_chat_sessions" => {
        let page = args.take("page").map_err(|e| format!("db_list_chat_sessions: bad argument `page`: {e}"))?;
        let limit = args.take("limit").map_err(|e| format!("db_list_chat_sessions: bad argument `limit`: {e}"))?;
        let archived = args.take("archived").map_err(|e| format!("db_list_chat_sessions: bad argument `archived`: {e}"))?;
        let date_from = args.take("date_from").map_err(|e| format!("db_list_chat_sessions: bad argument `date_from`: {e}"))?;
        let date_to = args.take("date_to").map_err(|e| format!("db_list_chat_sessions: bad argument `date_to`: {e}"))?;
        let out = db::chat::db_list_chat_sessions(page, limit, archived, date_from, date_to, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_get_chat_session" => {
        let id = args.take("id").map_err(|e| format!("db_get_chat_session: bad argument `id`: {e}"))?;
        let out = db::chat::db_get_chat_session(id, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_upsert_chat_session" => {
        let id = args.take("id").map_err(|e| format!("db_upsert_chat_session: bad argument `id`: {e}"))?;
        let title = args.take("title").map_err(|e| format!("db_upsert_chat_session: bad argument `title`: {e}"))?;
        let messages = args.take("messages").map_err(|e| format!("db_upsert_chat_session: bad argument `messages`: {e}"))?;
        let system_prompt = args.take("system_prompt").map_err(|e| format!("db_upsert_chat_session: bad argument `system_prompt`: {e}"))?;
        let preset_id = args.take("preset_id").map_err(|e| format!("db_upsert_chat_session: bad argument `preset_id`: {e}"))?;
        let provider_id = args.take("provider_id").map_err(|e| format!("db_upsert_chat_session: bad argument `provider_id`: {e}"))?;
        let message_count = args.take("message_count").map_err(|e| format!("db_upsert_chat_session: bad argument `message_count`: {e}"))?;
        let out = db::chat::db_upsert_chat_session(id, title, messages, system_prompt, preset_id, provider_id, message_count, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_delete_chat_session" => {
        let id = args.take("id").map_err(|e| format!("db_delete_chat_session: bad argument `id`: {e}"))?;
        let out = db::chat::db_delete_chat_session(id, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_set_chat_session_archived" => {
        let id = args.take("id").map_err(|e| format!("db_set_chat_session_archived: bad argument `id`: {e}"))?;
        let archived = args.take("archived").map_err(|e| format!("db_set_chat_session_archived: bad argument `archived`: {e}"))?;
        let out = db::chat::db_set_chat_session_archived(id, archived, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_set_chat_session_pinned" => {
        let id = args.take("id").map_err(|e| format!("db_set_chat_session_pinned: bad argument `id`: {e}"))?;
        let pinned = args.take("pinned").map_err(|e| format!("db_set_chat_session_pinned: bad argument `pinned`: {e}"))?;
        let out = db::chat::db_set_chat_session_pinned(id, pinned, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_rename_chat_session" => {
        let id = args.take("id").map_err(|e| format!("db_rename_chat_session: bad argument `id`: {e}"))?;
        let title = args.take("title").map_err(|e| format!("db_rename_chat_session: bad argument `title`: {e}"))?;
        let out = db::chat::db_rename_chat_session(id, title, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_save_reading_article" => {
        let title = args.take("title").map_err(|e| format!("db_save_reading_article: bad argument `title`: {e}"))?;
        let content = args.take("content").map_err(|e| format!("db_save_reading_article: bad argument `content`: {e}"))?;
        let source = args.take("source").map_err(|e| format!("db_save_reading_article: bad argument `source`: {e}"))?;
        let source_url = args.take("source_url").map_err(|e| format!("db_save_reading_article: bad argument `source_url`: {e}"))?;
        let tags = args.take("tags").map_err(|e| format!("db_save_reading_article: bad argument `tags`: {e}"))?;
        let out = db::reading::db_save_reading_article(title, content, source, source_url, tags, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_list_reading_articles" => {
        let search = args.take("search").map_err(|e| format!("db_list_reading_articles: bad argument `search`: {e}"))?;
        let source = args.take("source").map_err(|e| format!("db_list_reading_articles: bad argument `source`: {e}"))?;
        let date_from = args.take("date_from").map_err(|e| format!("db_list_reading_articles: bad argument `date_from`: {e}"))?;
        let date_to = args.take("date_to").map_err(|e| format!("db_list_reading_articles: bad argument `date_to`: {e}"))?;
        let only_commented = args.take("only_commented").map_err(|e| format!("db_list_reading_articles: bad argument `only_commented`: {e}"))?;
        let sort = args.take("sort").map_err(|e| format!("db_list_reading_articles: bad argument `sort`: {e}"))?;
        let page = args.take("page").map_err(|e| format!("db_list_reading_articles: bad argument `page`: {e}"))?;
        let limit = args.take("limit").map_err(|e| format!("db_list_reading_articles: bad argument `limit`: {e}"))?;
        let out = db::reading::db_list_reading_articles(search, source, date_from, date_to, only_commented, sort, page, limit, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_get_reading_article" => {
        let id = args.take("id").map_err(|e| format!("db_get_reading_article: bad argument `id`: {e}"))?;
        let touch = args.take("touch").map_err(|e| format!("db_get_reading_article: bad argument `touch`: {e}"))?;
        let out = db::reading::db_get_reading_article(id, touch, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_delete_reading_article" => {
        let id = args.take("id").map_err(|e| format!("db_delete_reading_article: bad argument `id`: {e}"))?;
        let out = db::reading::db_delete_reading_article(id, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_list_reading_comments" => {
        let article_id = args.take("article_id").map_err(|e| format!("db_list_reading_comments: bad argument `article_id`: {e}"))?;
        let out = db::reading::db_list_reading_comments(article_id, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_add_reading_comment" => {
        let article_id = args.take("article_id").map_err(|e| format!("db_add_reading_comment: bad argument `article_id`: {e}"))?;
        let author = args.take("author").map_err(|e| format!("db_add_reading_comment: bad argument `author`: {e}"))?;
        let body = args.take("body").map_err(|e| format!("db_add_reading_comment: bad argument `body`: {e}"))?;
        let anchor_text = args.take("anchor_text").map_err(|e| format!("db_add_reading_comment: bad argument `anchor_text`: {e}"))?;
        let out = db::reading::db_add_reading_comment(article_id, author, body, anchor_text, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_delete_reading_comment" => {
        let id = args.take("id").map_err(|e| format!("db_delete_reading_comment: bad argument `id`: {e}"))?;
        let out = db::reading::db_delete_reading_comment(id, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_search_chat_sessions" => {
        let query = args.take("query").map_err(|e| format!("db_search_chat_sessions: bad argument `query`: {e}"))?;
        let out = db::chat::db_search_chat_sessions(query, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_save_article_analysis" => {
        let title = args.take("title").map_err(|e| format!("db_save_article_analysis: bad argument `title`: {e}"))?;
        let source_url = args.take("source_url").map_err(|e| format!("db_save_article_analysis: bad argument `source_url`: {e}"))?;
        let origin = args.take("origin").map_err(|e| format!("db_save_article_analysis: bad argument `origin`: {e}"))?;
        let content = args.take("content").map_err(|e| format!("db_save_article_analysis: bad argument `content`: {e}"))?;
        let analysis_markdown = args.take("analysis_markdown").map_err(|e| format!("db_save_article_analysis: bad argument `analysis_markdown`: {e}"))?;
        let hn_item_id = args.take("hn_item_id").map_err(|e| format!("db_save_article_analysis: bad argument `hn_item_id`: {e}"))?;
        let out = db::articles::db_save_article_analysis(title, source_url, origin, content, analysis_markdown, hn_item_id, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_add_known_words" => {
        let words = args.take("words").map_err(|e| format!("db_add_known_words: bad argument `words`: {e}"))?;
        let source = args.take("source").map_err(|e| format!("db_add_known_words: bad argument `source`: {e}"))?;
        let out = db::articles::db_add_known_words(words, source, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_get_known_words" => {

        let out = db::articles::db_get_known_words(ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_dashboard_stats" => {

        let out = db::dashboard::db_dashboard_stats(ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_get_db_path" => {

        let out = db::settings::db_get_db_path(ctx.state::<AppState>())?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_get_db_size" => {

        let out = db::settings::db_get_db_size(ctx.state::<AppState>())?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_get_connection" => {

        let out = db::settings::db_get_connection(ctx.state::<AppState>())?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_connect_turso" => {
        let url = args.take("url").map_err(|e| format!("db_connect_turso: bad argument `url`: {e}"))?;
        let token = args.take("token").map_err(|e| format!("db_connect_turso: bad argument `token`: {e}"))?;
        let out = db::settings::db_connect_turso(url, token, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_disconnect_remote" => {

        let out = db::settings::db_disconnect_remote(ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_sync_now" => {

        let out = db::settings::db_sync_now(ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_import_analyze" => {
        let source_path = args.take("source_path").map_err(|e| format!("db_import_analyze: bad argument `source_path`: {e}"))?;
        let out = db::import::analyze::db_import_analyze(source_path, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_import_apply" => {
        let source_path = args.take("source_path").map_err(|e| format!("db_import_apply: bad argument `source_path`: {e}"))?;
        let decisions = args.take("decisions").map_err(|e| format!("db_import_apply: bad argument `decisions`: {e}"))?;
        let out = db::import::apply::db_import_apply(source_path, decisions, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_export_backup" => {
        let dest = args.take("dest").map_err(|e| format!("db_export_backup: bad argument `dest`: {e}"))?;
        let out = db::settings::db_export_backup(dest, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_clear_translations" => {

        let out = db::settings::db_clear_translations(ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_add_words_batch" => {
        let words = args.take("words").map_err(|e| format!("db_add_words_batch: bad argument `words`: {e}"))?;
        let source = args.take("source").map_err(|e| format!("db_add_words_batch: bad argument `source`: {e}"))?;
        let tag = args.take("tag").map_err(|e| format!("db_add_words_batch: bad argument `tag`: {e}"))?;
        let out = db::words_write::db_add_words_batch(words, source, tag, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_get_due_cards" => {
        let new_limit = args.take("new_limit").map_err(|e| format!("db_get_due_cards: bad argument `new_limit`: {e}"))?;
        let out = db::srs::db_get_due_cards(new_limit, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_review_card" => {
        let word_id = args.take("word_id").map_err(|e| format!("db_review_card: bad argument `word_id`: {e}"))?;
        let rating = args.take("rating").map_err(|e| format!("db_review_card: bad argument `rating`: {e}"))?;
        let out = db::srs::db_review_card(word_id, rating, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_add_search_history" => {
        let word = args.take("word").map_err(|e| format!("db_add_search_history: bad argument `word`: {e}"))?;
        let out = db::search_history::db_add_search_history(word, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_get_search_history" => {

        let out = db::search_history::db_get_search_history(ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_clear_search_history" => {

        let out = db::search_history::db_clear_search_history(ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_switch_path" => {
        let new_path = args.take("new_path").map_err(|e| format!("db_switch_path: bad argument `new_path`: {e}"))?;
        let out = db::settings::db_switch_path(new_path, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_get_startup_warning" => {

        let out = db::settings::db_get_startup_warning(ctx.state::<AppState>())?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_saved_profile_is_turso" => {

        let out = db::settings::db_saved_profile_is_turso()?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_forget_saved_profile" => {

        let out = db::settings::db_forget_saved_profile()?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_list_scenes" => {

        let out = db::scene_lab::db_list_scenes(ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_get_scene_lesson" => {
        let lesson_id = args.take("lesson_id").map_err(|e| format!("db_get_scene_lesson: bad argument `lesson_id`: {e}"))?;
        let out = db::scene_lab::db_get_scene_lesson(lesson_id, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_save_scene_lesson" => {
        let input = args.take("input").map_err(|e| format!("db_save_scene_lesson: bad argument `input`: {e}"))?;
        let out = db::scene_lab::db_save_scene_lesson(input, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_start_scene_session" => {
        let lesson_id = args.take("lesson_id").map_err(|e| format!("db_start_scene_session: bad argument `lesson_id`: {e}"))?;
        let mode = args.take("mode").map_err(|e| format!("db_start_scene_session: bad argument `mode`: {e}"))?;
        let out = db::scene_lab::db_start_scene_session(lesson_id, mode, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_finish_scene_session" => {
        let session_id = args.take("session_id").map_err(|e| format!("db_finish_scene_session: bad argument `session_id`: {e}"))?;
        let out = db::scene_lab::db_finish_scene_session(session_id, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_save_scene_attempt" => {
        let session_id = args.take("session_id").map_err(|e| format!("db_save_scene_attempt: bad argument `session_id`: {e}"))?;
        let scene_vocabulary_id = args.take("scene_vocabulary_id").map_err(|e| format!("db_save_scene_attempt: bad argument `scene_vocabulary_id`: {e}"))?;
        let mode = args.take("mode").map_err(|e| format!("db_save_scene_attempt: bad argument `mode`: {e}"))?;
        let correct = args.take("correct").map_err(|e| format!("db_save_scene_attempt: bad argument `correct`: {e}"))?;
        let response_ms = args.take("response_ms").map_err(|e| format!("db_save_scene_attempt: bad argument `response_ms`: {e}"))?;
        let hints_used = args.take("hints_used").map_err(|e| format!("db_save_scene_attempt: bad argument `hints_used`: {e}"))?;
        let out = db::scene_lab::db_save_scene_attempt(session_id, scene_vocabulary_id, mode, correct, response_ms, hints_used, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_get_scene_progress" => {
        let lesson_id = args.take("lesson_id").map_err(|e| format!("db_get_scene_progress: bad argument `lesson_id`: {e}"))?;
        let out = db::scene_lab::db_get_scene_progress(lesson_id, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_add_scene_words_to_vocabulary" => {
        let scene_vocabulary_ids = args.take("scene_vocabulary_ids").map_err(|e| format!("db_add_scene_words_to_vocabulary: bad argument `scene_vocabulary_ids`: {e}"))?;
        let out = db::scene_lab::db_add_scene_words_to_vocabulary(scene_vocabulary_ids, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_save_sentence_pattern" => {
        let sentence = args.take("sentence").map_err(|e| format!("db_save_sentence_pattern: bad argument `sentence`: {e}"))?;
        let zh = args.take("zh").map_err(|e| format!("db_save_sentence_pattern: bad argument `zh`: {e}"))?;
        let skeleton = args.take("skeleton").map_err(|e| format!("db_save_sentence_pattern: bad argument `skeleton`: {e}"))?;
        let note = args.take("note").map_err(|e| format!("db_save_sentence_pattern: bad argument `note`: {e}"))?;
        let level = args.take("level").map_err(|e| format!("db_save_sentence_pattern: bad argument `level`: {e}"))?;
        let source = args.take("source").map_err(|e| format!("db_save_sentence_pattern: bad argument `source`: {e}"))?;
        let out = db::patterns::db_save_sentence_pattern(sentence, zh, skeleton, note, level, source, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_list_patterns" => {

        let out = db::patterns::db_list_patterns(ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_delete_pattern" => {
        let pattern_id = args.take("pattern_id").map_err(|e| format!("db_delete_pattern: bad argument `pattern_id`: {e}"))?;
        let out = db::patterns::db_delete_pattern(pattern_id, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_update_pattern_analysis" => {
        let pattern_id = args.take("pattern_id").map_err(|e| format!("db_update_pattern_analysis: bad argument `pattern_id`: {e}"))?;
        let zh = args.take("zh").map_err(|e| format!("db_update_pattern_analysis: bad argument `zh`: {e}"))?;
        let skeleton = args.take("skeleton").map_err(|e| format!("db_update_pattern_analysis: bad argument `skeleton`: {e}"))?;
        let note = args.take("note").map_err(|e| format!("db_update_pattern_analysis: bad argument `note`: {e}"))?;
        let level = args.take("level").map_err(|e| format!("db_update_pattern_analysis: bad argument `level`: {e}"))?;
        let out = db::patterns::db_update_pattern_analysis(pattern_id, zh, skeleton, note, level, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_set_pattern_starred" => {
        let pattern_id = args.take("pattern_id").map_err(|e| format!("db_set_pattern_starred: bad argument `pattern_id`: {e}"))?;
        let starred = args.take("starred").map_err(|e| format!("db_set_pattern_starred: bad argument `starred`: {e}"))?;
        let out = db::patterns::db_set_pattern_starred(pattern_id, starred, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "tts_scan_models" => {
        let extra_dirs = args.take("extra_dirs").map_err(|e| format!("tts_scan_models: bad argument `extra_dirs`: {e}"))?;
        let out = ttsels::tts_scan_models(extra_dirs)?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "tts_default_models_dir" => {

        let out = ttsels::tts_default_models_dir()?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "tts_load_model" => {
        let path = args.take("path").map_err(|e| format!("tts_load_model: bad argument `path`: {e}"))?;
        let out = tts::engine::tts_load_model(ctx.state::<crate::AppState>(), path).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "tts_delete_model" => {
        let path = args.take("path").map_err(|e| format!("tts_delete_model: bad argument `path`: {e}"))?;
        let out = tts::engine::tts_delete_model(ctx.state::<crate::AppState>(), path)?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "tts_synthesize" => {
        let text = args.take("text").map_err(|e| format!("tts_synthesize: bad argument `text`: {e}"))?;
        let speaker_id = args.take("speaker_id").map_err(|e| format!("tts_synthesize: bad argument `speaker_id`: {e}"))?;
        let speed = args.take("speed").map_err(|e| format!("tts_synthesize: bad argument `speed`: {e}"))?;
        let out = tts::engine::tts_synthesize(ctx.state::<crate::AppState>(), text, speaker_id, speed).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "tts_engine_status" => {

        let out = tts::engine::tts_engine_status(ctx.state::<crate::AppState>())?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "tts_download_model" => {
        let url = args.take("url").map_err(|e| format!("tts_download_model: bad argument `url`: {e}"))?;
        let dirname = args.take("dirname").map_err(|e| format!("tts_download_model: bad argument `dirname`: {e}"))?;
        let out = tts::download::tts_download_model(ctx.app(), url, dirname).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "fetch_article" => {
        let url = args.take("url").map_err(|e| format!("fetch_article: bad argument `url`: {e}"))?;
        let out = reader::fetch_article(url).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "fetch_hn_comments" => {
        let story_id = args.take("story_id").map_err(|e| format!("fetch_hn_comments: bad argument `story_id`: {e}"))?;
        let out = hn::fetch_hn_comments(story_id).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "fetch_hn_section" => {
        let section = args.take("section").map_err(|e| format!("fetch_hn_section: bad argument `section`: {e}"))?;
        let offset = args.take("offset").map_err(|e| format!("fetch_hn_section: bad argument `offset`: {e}"))?;
        let limit = args.take("limit").map_err(|e| format!("fetch_hn_section: bad argument `limit`: {e}"))?;
        let out = hn::fetch_hn_section(section, offset, limit).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "search_hn" => {
        let query = args.take("query").map_err(|e| format!("search_hn: bad argument `query`: {e}"))?;
        let page = args.take("page").map_err(|e| format!("search_hn: bad argument `page`: {e}"))?;
        let out = hn::search_hn(query, page).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "secret_get" => {
        let key = args.take("key").map_err(|e| format!("secret_get: bad argument `key`: {e}"))?;
        let out = secrets::secret_get(key)?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "secret_set" => {
        let key = args.take("key").map_err(|e| format!("secret_set: bad argument `key`: {e}"))?;
        let value = args.take("value").map_err(|e| format!("secret_set: bad argument `value`: {e}"))?;
        let out = secrets::secret_set(key, value)?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "secret_delete" => {
        let key = args.take("key").map_err(|e| format!("secret_delete: bad argument `key`: {e}"))?;
        let out = secrets::secret_delete(key)?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "fetch_rss" => {
        let url = args.take("url").map_err(|e| format!("fetch_rss: bad argument `url`: {e}"))?;
        let out = rss::parse::fetch_rss(url).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_add_rss_feed" => {
        let url = args.take("url").map_err(|e| format!("db_add_rss_feed: bad argument `url`: {e}"))?;
        let title = args.take("title").map_err(|e| format!("db_add_rss_feed: bad argument `title`: {e}"))?;
        let site_link = args.take("site_link").map_err(|e| format!("db_add_rss_feed: bad argument `site_link`: {e}"))?;
        let description = args.take("description").map_err(|e| format!("db_add_rss_feed: bad argument `description`: {e}"))?;
        let out = rss::commands::db_add_rss_feed(url, title, site_link, description, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_get_rss_feeds" => {

        let out = rss::commands::db_get_rss_feeds(ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_update_rss_feed_title" => {
        let id = args.take("id").map_err(|e| format!("db_update_rss_feed_title: bad argument `id`: {e}"))?;
        let title = args.take("title").map_err(|e| format!("db_update_rss_feed_title: bad argument `title`: {e}"))?;
        let out = rss::commands::db_update_rss_feed_title(id, title, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_update_rss_feed_preferences" => {
        let id = args.take("id").map_err(|e| format!("db_update_rss_feed_preferences: bad argument `id`: {e}"))?;
        let category = args.take("category").map_err(|e| format!("db_update_rss_feed_preferences: bad argument `category`: {e}"))?;
        let is_pinned = args.take("is_pinned").map_err(|e| format!("db_update_rss_feed_preferences: bad argument `is_pinned`: {e}"))?;
        let out = rss::commands::db_update_rss_feed_preferences(id, category, is_pinned, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_delete_rss_feed" => {
        let id = args.take("id").map_err(|e| format!("db_delete_rss_feed: bad argument `id`: {e}"))?;
        let out = rss::commands::db_delete_rss_feed(id, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_sync_rss_feed" => {
        let feed_id = args.take("feed_id").map_err(|e| format!("db_sync_rss_feed: bad argument `feed_id`: {e}"))?;
        let out = rss::commands::db_sync_rss_feed(feed_id, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_get_rss_entries" => {
        let feed_id = args.take("feed_id").map_err(|e| format!("db_get_rss_entries: bad argument `feed_id`: {e}"))?;
        let limit = args.take("limit").map_err(|e| format!("db_get_rss_entries: bad argument `limit`: {e}"))?;
        let offset = args.take("offset").map_err(|e| format!("db_get_rss_entries: bad argument `offset`: {e}"))?;
        let out = rss::commands::db_get_rss_entries(feed_id, limit, offset, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_mark_rss_entry_read" => {
        let id = args.take("id").map_err(|e| format!("db_mark_rss_entry_read: bad argument `id`: {e}"))?;
        let out = rss::commands::db_mark_rss_entry_read(id, ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "db_get_rss_unread_counts" => {

        let out = rss::commands::db_get_rss_unread_counts(ctx.state::<AppState>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "music_scan_library" => {
        let root = args.take("root").map_err(|e| format!("music_scan_library: bad argument `root`: {e}"))?;
        let out = music::music_scan_library(root).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "native_audio_probe_duration" => {
        let path = args.take("path").map_err(|e| format!("native_audio_probe_duration: bad argument `path`: {e}"))?;
        let out = tokio::task::spawn_blocking(move || native_audio::native_audio_probe_duration(path)).await.map_err(|e| e.to_string())??;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "native_audio_load" => {
        let path = args.take("path").map_err(|e| format!("native_audio_load: bad argument `path`: {e}"))?;
        let autoplay = args.take("autoplay").map_err(|e| format!("native_audio_load: bad argument `autoplay`: {e}"))?;
        let out = native_audio::native_audio_load(path, autoplay, ctx.state::<NativeAudioState>())?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "native_audio_play" => {

        let out = native_audio::native_audio_play(ctx.state::<NativeAudioState>())?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "native_audio_pause" => {

        let out = native_audio::native_audio_pause(ctx.state::<NativeAudioState>())?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "native_audio_seek" => {
        let seconds = args.take("seconds").map_err(|e| format!("native_audio_seek: bad argument `seconds`: {e}"))?;
        let out = native_audio::native_audio_seek(seconds, ctx.state::<NativeAudioState>())?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "native_audio_set_speed" => {
        let speed = args.take("speed").map_err(|e| format!("native_audio_set_speed: bad argument `speed`: {e}"))?;
        let out = native_audio::native_audio_set_speed(speed, ctx.state::<NativeAudioState>())?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "native_audio_stop" => {

        let out = native_audio::native_audio_stop(ctx.state::<NativeAudioState>())?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "native_audio_snapshot" => {

        let out = native_audio::native_audio_snapshot(ctx.state::<NativeAudioState>())?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "localdocs_list" => {
        let root = args.take("root").map_err(|e| format!("localdocs_list: bad argument `root`: {e}"))?;
        let out = localdocs::list_search::localdocs_list(root)?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "localdocs_root_exists" => {
        let root = args.take("root").map_err(|e| format!("localdocs_root_exists: bad argument `root`: {e}"))?;
        let out = localdocs::list_search::localdocs_root_exists(root)?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "localdocs_store_asset" => {
        let root = args.take("root").map_err(|e| format!("localdocs_store_asset: bad argument `root`: {e}"))?;
        let file_name = args.take("file_name").map_err(|e| format!("localdocs_store_asset: bad argument `file_name`: {e}"))?;
        let mime_type = args.take("mime_type").map_err(|e| format!("localdocs_store_asset: bad argument `mime_type`: {e}"))?;
        let data_base64 = args.take("data_base64").map_err(|e| format!("localdocs_store_asset: bad argument `data_base64`: {e}"))?;
        let out = localdocs::markdown_io::localdocs_store_asset(root, file_name, mime_type, data_base64)?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "localdocs_search" => {
        let root = args.take("root").map_err(|e| format!("localdocs_search: bad argument `root`: {e}"))?;
        let query = args.take("query").map_err(|e| format!("localdocs_search: bad argument `query`: {e}"))?;
        let out = localdocs::list_search::localdocs_search(root, query)?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "localdocs_read" => {
        let root = args.take("root").map_err(|e| format!("localdocs_read: bad argument `root`: {e}"))?;
        let rel_path = args.take("rel_path").map_err(|e| format!("localdocs_read: bad argument `rel_path`: {e}"))?;
        let out = localdocs::crud::localdocs_read(root, rel_path)?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "localdocs_write" => {
        let root = args.take("root").map_err(|e| format!("localdocs_write: bad argument `root`: {e}"))?;
        let rel_path = args.take("rel_path").map_err(|e| format!("localdocs_write: bad argument `rel_path`: {e}"))?;
        let content = args.take("content").map_err(|e| format!("localdocs_write: bad argument `content`: {e}"))?;
        let out = localdocs::crud::localdocs_write(root, rel_path, content)?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "localdocs_create" => {
        let root = args.take("root").map_err(|e| format!("localdocs_create: bad argument `root`: {e}"))?;
        let name = args.take("name").map_err(|e| format!("localdocs_create: bad argument `name`: {e}"))?;
        let directory = args.take("directory").map_err(|e| format!("localdocs_create: bad argument `directory`: {e}"))?;
        let out = localdocs::crud::localdocs_create(root, name, directory)?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "localdocs_move" => {
        let root = args.take("root").map_err(|e| format!("localdocs_move: bad argument `root`: {e}"))?;
        let rel_path = args.take("rel_path").map_err(|e| format!("localdocs_move: bad argument `rel_path`: {e}"))?;
        let target_dir = args.take("target_dir").map_err(|e| format!("localdocs_move: bad argument `target_dir`: {e}"))?;
        let out = localdocs::crud::localdocs_move(root, rel_path, target_dir)?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "localdocs_rename" => {
        let root = args.take("root").map_err(|e| format!("localdocs_rename: bad argument `root`: {e}"))?;
        let rel_path = args.take("rel_path").map_err(|e| format!("localdocs_rename: bad argument `rel_path`: {e}"))?;
        let new_name = args.take("new_name").map_err(|e| format!("localdocs_rename: bad argument `new_name`: {e}"))?;
        let out = localdocs::crud::localdocs_rename(root, rel_path, new_name)?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "localdocs_delete" => {
        let root = args.take("root").map_err(|e| format!("localdocs_delete: bad argument `root`: {e}"))?;
        let rel_path = args.take("rel_path").map_err(|e| format!("localdocs_delete: bad argument `rel_path`: {e}"))?;
        let out = localdocs::crud::localdocs_delete(root, rel_path)?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "localdocs_import" => {
        let root = args.take("root").map_err(|e| format!("localdocs_import: bad argument `root`: {e}"))?;
        let sources = args.take("sources").map_err(|e| format!("localdocs_import: bad argument `sources`: {e}"))?;
        let out = localdocs::import_export::localdocs_import(root, sources)?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "localdocs_export" => {
        let root = args.take("root").map_err(|e| format!("localdocs_export: bad argument `root`: {e}"))?;
        let rel_paths = args.take("rel_paths").map_err(|e| format!("localdocs_export: bad argument `rel_paths`: {e}"))?;
        let destination = args.take("destination").map_err(|e| format!("localdocs_export: bad argument `destination`: {e}"))?;
        let out = localdocs::import_export::localdocs_export(root, rel_paths, destination)?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "markdown_read_files" => {
        let paths = args.take("paths").map_err(|e| format!("markdown_read_files: bad argument `paths`: {e}"))?;
        let out = localdocs::markdown_io::markdown_read_files(paths)?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "markdown_export_files" => {
        let destination = args.take("destination").map_err(|e| format!("markdown_export_files: bad argument `destination`: {e}"))?;
        let files = args.take("files").map_err(|e| format!("markdown_export_files: bad argument `files`: {e}"))?;
        let out = localdocs::markdown_io::markdown_export_files(destination, files)?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "markdown_export_bundles" => {
        let destination = args.take("destination").map_err(|e| format!("markdown_export_bundles: bad argument `destination`: {e}"))?;
        let files = args.take("files").map_err(|e| format!("markdown_export_bundles: bad argument `files`: {e}"))?;
        let out = localdocs::markdown_io::markdown_export_bundles(destination, files)?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "mcp_get_config" => {

        let out = mcp::controller::mcp_get_config(ctx.state::<crate::AppState>(), ctx.state::<McpController>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "mcp_apply_config" => {
        let config = args.take("config").map_err(|e| format!("mcp_apply_config: bad argument `config`: {e}"))?;
        let out = mcp::controller::mcp_apply_config(config, ctx.app(), ctx.state::<crate::AppState>(), ctx.state::<McpController>()).await?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    },
    "mcp_generate_token" => {

        let out = mcp::config::mcp_generate_token()?;
        Ok(serde_json::to_value(out).map_err(|e| e.to_string())?)
    }
    other => Err(format!("unknown command `{other}`")),
    }
}
