import React, { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { Dialog, DialogTitle } from "@/components/ui/dialog";
import { useDiscover, GeneratedWord, WordFamily } from "@/hooks/useDiscover";
import { useDB } from "@/hooks/useDB";
import { useT } from "@/hooks/useT";
import { useWordModalStore } from "@/store/wordModalStore";
import { LevelBadge } from "@/components/shared/LevelBadge";
import { SpeakButton } from "@/components/ui/SpeakButton";
import { SparkIcon, CloseIcon } from "@/components/ui/icons";
import { Button } from "@/components/ui/button";

const COUNTS = [10, 20, 50, 100];

// Shown instantly while the AI-generated chip suggestions are loading, and
// as a fallback if that call fails (no provider configured, network error).
const FALLBACK_TOPICS = ["Programming", "System Design", "DevOps", "Machine Learning", "Frontend", "Databases", "Security", "Startup & VC", "AI"];
const FALLBACK_ROOTS = ["-spect", "-ject", "-duct", "-mit", "bene-", "trans-", "-vert", "circum-"];

/** If a generation batch nets fewer than this many genuinely-new words (e.g.
 * the topic's common vocabulary is already mostly in the library), retry
 * automatically with a bigger, escalating batch instead of leaving the user
 * with an almost-all-duplicate result. */
const MIN_NEW_WORDS = 5;
const MAX_ATTEMPTS = 3;

interface Props {
  open: boolean;
  onClose: () => void;
  /** Lowercased existing vocabulary — generated results are deduped against this. */
  existingWords: Set<string>;
  /** Called after a successful add so the caller can refresh its word list. */
  onAdded: () => void;
}

export function GenerateVocabModal({ open, onClose, existingWords, onAdded }: Props) {
  const { generateTopicVocabulary, generateWordFamily, generateTopicSuggestions, generateRootSuggestions, isGenerating, isGeneratingFamily } = useDiscover();
  const db = useDB();
  const t = useT();
  const openWordModal = useWordModalStore((s) => s.openWordModal);

  const [mode, setMode] = useState<"topic" | "family">("topic");

  // Chip suggestions — regenerated by AI every time the modal opens, instead
  // of being a fixed static list.
  const [topicChips, setTopicChips] = useState<string[]>(FALLBACK_TOPICS);
  const [rootChips, setRootChips] = useState<string[]>(FALLBACK_ROOTS);
  const [chipsLoading, setChipsLoading] = useState(false);

  useEffect(() => {
    if (!open) return;
    setChipsLoading(true);
    Promise.allSettled([generateTopicSuggestions(), generateRootSuggestions()]).then(([t1, t2]) => {
      if (t1.status === "fulfilled" && Array.isArray(t1.value) && t1.value.length > 0) setTopicChips(t1.value);
      if (t2.status === "fulfilled" && Array.isArray(t2.value) && t2.value.length > 0) setRootChips(t2.value);
      setChipsLoading(false);
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open]);

  // ── Topic-batch generation ────────────────────────────────────────────────

  const [topic, setTopic] = useState("");
  const [selectedTopic, setSelectedTopic] = useState("");
  const [count, setCount] = useState(50);
  const [generated, setGenerated] = useState<GeneratedWord[]>([]);
  const [generatedTopic, setGeneratedTopic] = useState("");
  const [selectedGen, setSelectedGen] = useState<Set<string>>(new Set());
  const [addedWords, setAddedWords] = useState<Set<string>>(new Set());
  const [saving, setSaving] = useState(false);

  const isKnown = (word: string) => existingWords.has(word.toLowerCase()) || addedWords.has(word.toLowerCase());
  const newGenerated = useMemo(() => generated.filter((w) => !isKnown(w.word)), [generated, existingWords, addedWords]);

  const handleGenerate = async () => {
    const topicVal = topic.trim() || selectedTopic || topicChips[0];
    if (!topicVal || isGenerating) return;
    setGenerated([]);
    setAddedWords(new Set());
    const toastId = toast.loading(t("discover.generating"));
    try {
      // seen: every word the model has returned so far this run (lowercased) —
      // fed back as part of the exclude list so a retry doesn't just get the
      // same words again.
      const seen = new Set<string>();
      const all: GeneratedWord[] = [];
      let requestSize = count;
      let newCount = 0;

      for (let attempt = 0; attempt < MAX_ATTEMPTS; attempt++) {
        const exclude = Array.from(new Set([...existingWords, ...seen]));
        const batch = await generateTopicVocabulary(topicVal, requestSize, exclude);
        for (const w of batch) {
          const key = w.word.toLowerCase();
          if (seen.has(key)) continue;
          seen.add(key);
          all.push(w);
        }
        newCount = all.filter((w) => !isKnown(w.word)).length;
        if (newCount >= MIN_NEW_WORDS) break;
        // Escalate the batch size on retry — repeating the same small count
        // against an already well-covered topic tends to repeat itself too.
        requestSize = Math.min(Math.max(requestSize * 2, 50), 100);
      }

      setGenerated(all);
      setGeneratedTopic(topicVal);
      setSelectedGen(new Set(all.filter((w) => !isKnown(w.word)).map((w) => w.word)));
      if (newCount < MIN_NEW_WORDS) {
        toast.info(t("discover.mostlyDuplicate", { n: newCount }), { id: toastId });
      } else {
        toast.success(t("discover.generatedOk", { n: all.length }), { id: toastId });
      }
    } catch (e: any) {
      toast.error(e.message || t("discover.errFail"), { id: toastId });
    }
  };

  const saveSelected = async () => {
    const picked = generated.filter((g) => selectedGen.has(g.word) && !isKnown(g.word));
    if (picked.length === 0 || saving) return;
    setSaving(true);
    try {
      const result = await db.addWordsBatch(
        picked.map((w) => ({ word: w.word, zh: w.zh, level: w.level, context: w.example })),
        "discover",
        generatedTopic
      );
      if (result.added > 0) {
        window.dispatchEvent(new CustomEvent("vocab-updated"));
        setAddedWords((prev) => {
          const next = new Set(prev);
          picked.forEach((w) => next.add(w.word.toLowerCase()));
          return next;
        });
        onAdded();
      }
      setSelectedGen(new Set());
      toast.success(t("discover.addedOk", { n: result.added }));
    } finally {
      setSaving(false);
    }
  };

  // ── Word family (root/affix) explorer ───────────────────────────────────

  const [rootInput, setRootInput] = useState("");
  const [family, setFamily] = useState<WordFamily | null>(null);
  const [savingFamily, setSavingFamily] = useState(false);
  const [addedFamilyWords, setAddedFamilyWords] = useState<Set<string>>(new Set());

  const isFamilyWordKnown = (word: string) => existingWords.has(word.toLowerCase()) || addedFamilyWords.has(word.toLowerCase());

  const exploreRoot = async (root: string) => {
    if (!root.trim() || isGeneratingFamily) return;
    setRootInput(root);
    const toastId = toast.loading(t("discover.family.loading"));
    try {
      const result = await generateWordFamily(root.trim());
      setFamily(result);
      setAddedFamilyWords(new Set());
      toast.success(t("discover.family.ok", { n: result.words.length }), { id: toastId });
    } catch (e: any) {
      toast.error(e.message || t("discover.errFail"), { id: toastId });
    }
  };

  const addFamilyWord = async (w: { word: string; zh: string; level: string; breakdown: string }) => {
    const result = await db.addWordsBatch(
      [{ word: w.word, zh: w.zh, level: w.level, context: w.breakdown }],
      "discover",
      family?.root
    );
    if (result.added > 0) {
      window.dispatchEvent(new CustomEvent("vocab-updated"));
      setAddedFamilyWords((prev) => new Set(prev).add(w.word.toLowerCase()));
      onAdded();
      toast.success(t("discover.addedOk", { n: 1 }));
    } else {
      toast.info(t("discover.alreadyIn", { word: w.word }));
    }
  };

  const addAllFamilyWords = async () => {
    if (!family || savingFamily) return;
    const pending = family.words.filter((w) => !isFamilyWordKnown(w.word));
    if (pending.length === 0) return;
    setSavingFamily(true);
    try {
      const result = await db.addWordsBatch(
        pending.map((w) => ({ word: w.word, zh: w.zh, level: w.level, context: w.breakdown })),
        "discover",
        family.root
      );
      if (result.added > 0) {
        window.dispatchEvent(new CustomEvent("vocab-updated"));
        setAddedFamilyWords((prev) => {
          const next = new Set(prev);
          pending.forEach((w) => next.add(w.word.toLowerCase()));
          return next;
        });
        onAdded();
      }
      toast.success(t("discover.addedOk", { n: result.added }));
    } finally {
      setSavingFamily(false);
    }
  };

  const handleClose = () => {
    onClose();
    // Reset generated results so reopening starts fresh.
    setGenerated([]);
    setSelectedGen(new Set());
    setAddedWords(new Set());
    setFamily(null);
    setAddedFamilyWords(new Set());
  };

  return (
    <Dialog open={open} onClose={handleClose} maxWidth="max-w-2xl">
      <div className="flex items-center justify-between px-6 pt-5 pb-3 border-b border-border">
        <div className="flex items-center gap-2">
          <SparkIcon className="w-3.5 h-3.5 text-primary" />
          <DialogTitle className="text-sm font-semibold">{t("discover.generateTitle")}</DialogTitle>
        </div>
        <Button
          variant="ghost"
          onClick={handleClose}
          className="w-7 h-7 p-0 rounded-full flex items-center justify-center text-muted-foreground hover:bg-muted hover:text-foreground transition-colors"
        >
          <CloseIcon className="w-3.5 h-3.5" />
        </Button>
      </div>

      {/* Tabs */}
      <div className="flex gap-1 px-6 pt-3">
        <Button
          variant="ghost"
          onClick={() => setMode("topic")}
          className={`h-auto px-3 py-1.5 text-xs font-semibold rounded-lg transition-colors ${
            mode === "topic" ? "bg-primary text-white hover:bg-primary" : "bg-muted text-muted-foreground hover:bg-muted/80"
          }`}
        >
          {t("discover.tabTopic")}
        </Button>
        <Button
          variant="ghost"
          onClick={() => setMode("family")}
          className={`h-auto px-3 py-1.5 text-xs font-semibold rounded-lg transition-colors ${
            mode === "family" ? "bg-primary text-white hover:bg-primary" : "bg-muted text-muted-foreground hover:bg-muted/80"
          }`}
        >
          {t("discover.tabFamily")}
        </Button>
      </div>

      <div className="p-6 space-y-4 max-h-[70vh] overflow-y-auto">
        {mode === "topic" ? (
          <>
            <div className="flex gap-2">
              <input
                type="text"
                value={topic}
                onChange={(e) => setTopic(e.target.value)}
                onKeyDown={(e) => e.key === "Enter" && handleGenerate()}
                placeholder={t("discover.placeholder")}
                className="flex-1 h-9 px-3 text-sm rounded-lg border border-input bg-background focus:outline-none focus:ring-2 focus:ring-primary/40 placeholder:text-muted-foreground"
              />
              <div className="flex items-center border border-input rounded-lg overflow-hidden shrink-0">
                {COUNTS.map((n) => (
                  <Button
                    key={n}
                    variant="ghost"
                    onClick={() => setCount(n)}
                    className={`h-9 px-3 rounded-none text-xs font-semibold transition-colors ${
                      count === n ? "bg-primary text-white hover:bg-primary" : "text-muted-foreground hover:bg-muted"
                    }`}
                  >
                    {t("discover.wordCount", { n })}
                  </Button>
                ))}
              </div>
              <Button
                onClick={handleGenerate}
                disabled={isGenerating}
                className="h-9 px-5 rounded-lg text-sm font-semibold bg-primary text-white hover:bg-primary/90 disabled:opacity-50 transition-colors shrink-0"
              >
                {isGenerating ? t("discover.generating") : t("discover.generate")}
              </Button>
            </div>

            <div className={`flex flex-wrap gap-1.5 transition-opacity ${chipsLoading ? "opacity-50" : ""}`}>
              {topicChips.map((topic_item) => (
                <Button
                  key={topic_item}
                  variant="ghost"
                  onClick={() => { setSelectedTopic(topic_item); setTopic(""); }}
                  className={`h-auto px-3 py-1 rounded-full text-xs font-medium border transition-colors ${
                    selectedTopic === topic_item && !topic
                      ? "bg-primary text-white border-primary hover:bg-primary"
                      : "border-border text-foreground hover:border-primary/50 hover:bg-transparent"
                  }`}
                >
                  {topic_item}
                </Button>
              ))}
            </div>

            {generated.length > 0 && (
              <div className="border border-border rounded-xl overflow-hidden">
                <div className="flex items-center justify-between px-4 py-2.5 border-b border-border bg-muted/20">
                  <div className="flex items-center gap-2">
                    <input
                      type="checkbox"
                      checked={selectedGen.size === newGenerated.length && newGenerated.length > 0}
                      onChange={() =>
                        selectedGen.size === newGenerated.length
                          ? setSelectedGen(new Set())
                          : setSelectedGen(new Set(newGenerated.map((w) => w.word)))
                      }
                      className="rounded"
                    />
                    <span className="text-sm font-semibold">{t("discover.results", { n: generated.length })}</span>
                    <span className="text-xs text-muted-foreground">{t("discover.selected", { n: selectedGen.size })}</span>
                  </div>
                  <Button
                    variant="link"
                    onClick={saveSelected}
                    disabled={selectedGen.size === 0 || saving}
                    className="h-auto p-0 text-xs font-semibold text-primary disabled:text-muted-foreground hover:underline"
                  >
                    {saving ? t("discover.saving") : t("discover.addToVocab")}
                  </Button>
                </div>
                <div className="divide-y divide-border max-h-96 overflow-y-auto">
                  {generated.map((w, i) => {
                    const known = isKnown(w.word);
                    return (
                      <div key={i} className={`flex items-center gap-3 px-4 py-2.5 ${known ? "opacity-45" : "hover:bg-muted/40"}`}>
                        <input
                          type="checkbox"
                          disabled={known}
                          checked={!known && selectedGen.has(w.word)}
                          onChange={() => {
                            setSelectedGen((prev) => {
                              const next = new Set(prev);
                              next.has(w.word) ? next.delete(w.word) : next.add(w.word);
                              return next;
                            });
                          }}
                          className="rounded shrink-0"
                        />
                        <div className="w-28 shrink-0 flex items-center gap-1">
                          <Button
                            variant="link"
                            onClick={() => openWordModal(w.word)}
                            className="h-auto p-0 font-semibold text-sm text-primary hover:underline"
                          >
                            {w.word}
                          </Button>
                          <SpeakButton text={w.word} className="w-3 h-3" />
                        </div>
                        <LevelBadge level={w.level} />
                        <span className="text-sm text-muted-foreground w-20 shrink-0 truncate">{w.zh}</span>
                        <span className="text-xs text-muted-foreground truncate flex-1">{w.example}</span>
                        {known && (
                          <span className="text-[10px] font-semibold text-emerald-600 dark:text-emerald-400 shrink-0">
                            {t("discover.inVocab")}
                          </span>
                        )}
                      </div>
                    );
                  })}
                </div>
              </div>
            )}
          </>
        ) : (
          <>
            <div className="flex gap-2">
              <input
                type="text"
                value={rootInput}
                onChange={(e) => setRootInput(e.target.value)}
                onKeyDown={(e) => e.key === "Enter" && exploreRoot(rootInput)}
                placeholder={t("discover.family.placeholder")}
                className="flex-1 h-9 px-3 text-sm rounded-lg border border-input bg-background focus:outline-none focus:ring-2 focus:ring-primary/40 placeholder:text-muted-foreground font-mono"
              />
              <Button
                onClick={() => exploreRoot(rootInput)}
                disabled={isGeneratingFamily || !rootInput.trim()}
                className="h-9 px-5 rounded-lg text-sm font-semibold bg-primary text-white hover:bg-primary/90 disabled:opacity-50 transition-colors shrink-0"
              >
                {isGeneratingFamily ? t("discover.family.loadingBtn") : t("discover.family.explore")}
              </Button>
            </div>
            <div className={`flex flex-wrap gap-1.5 transition-opacity ${chipsLoading ? "opacity-50" : ""}`}>
              {rootChips.map((r) => (
                <Button
                  key={r}
                  variant="ghost"
                  onClick={() => exploreRoot(r)}
                  disabled={isGeneratingFamily}
                  className="h-auto px-3 py-1 rounded-full text-xs font-mono border border-border text-foreground hover:border-primary/50 hover:bg-transparent disabled:opacity-50 transition-colors"
                >
                  {r}
                </Button>
              ))}
            </div>

            {family && (
              <div className="border border-border rounded-xl overflow-hidden">
                <div className="flex items-center gap-3 px-4 py-3 bg-muted/30 border-b border-border">
                  <span className="font-mono font-bold text-primary">{family.root}</span>
                  <span className="text-sm text-muted-foreground flex-1">{family.meaning}</span>
                  <Button
                    variant="link"
                    onClick={addAllFamilyWords}
                    disabled={savingFamily || family.words.every((w) => isFamilyWordKnown(w.word))}
                    className="h-auto p-0 text-xs font-semibold text-primary disabled:text-muted-foreground hover:underline shrink-0"
                  >
                    {savingFamily ? t("discover.saving") : t("discover.family.addAll")}
                  </Button>
                </div>
                <div className="grid grid-cols-1 sm:grid-cols-2 max-h-96 overflow-y-auto">
                  {family.words.map((w, i) => {
                    const known = isFamilyWordKnown(w.word);
                    return (
                      <div key={i} className={`px-4 py-3 space-y-1 border-t border-border first:border-t-0 sm:[&:nth-child(2)]:border-t-0 ${i % 2 === 0 ? "sm:border-r sm:border-border" : ""} ${known ? "opacity-45" : ""}`}>
                        <div className="flex items-center gap-2">
                          <Button
                            variant="link"
                            onClick={() => openWordModal(w.word)}
                            className="h-auto p-0 font-semibold text-sm text-primary hover:underline"
                          >
                            {w.word}
                          </Button>
                          <SpeakButton text={w.word} className="w-3 h-3" />
                          <LevelBadge level={w.level} />
                          <span className="text-xs text-muted-foreground truncate flex-1">{w.zh}</span>
                          {known ? (
                            <span className="text-[10px] font-semibold text-emerald-600 dark:text-emerald-400 shrink-0">
                              {t("discover.inVocab")}
                            </span>
                          ) : (
                            <Button
                              variant="link"
                              onClick={() => addFamilyWord(w)}
                              className="h-auto p-0 text-[11px] font-semibold text-primary hover:underline shrink-0"
                            >
                              + {t("discover.addOne")}
                            </Button>
                          )}
                        </div>
                        <p className="text-[11px] font-mono text-muted-foreground/70">{w.breakdown}</p>
                      </div>
                    );
                  })}
                </div>
              </div>
            )}
          </>
        )}
      </div>
    </Dialog>
  );
}
