// scripts/gen-schema.js — regenerates src/db/schema_sql.ts from src/db/schema.sql
//
// Emits TWO exports:
//   schema    (default) — full frozen desktop schema, for native (app.json
//             expo-sqlite plugin sets enableFTS: true).
//   schemaWeb — web variant. expo-sqlite's web wa-sqlite wasm is compiled
//             WITHOUT FTS5 (`USING fts5` throws "no such module: fts5"), so the
//             FTS virtual tables and their sync triggers are stripped. The
//             _fts_shadow tables stay (plain tables, harmless), search falls
//             back to LIKE (db/reading.ts, db/documents.ts).
//
// Both variants are sanitized:
// 1. Statements are parsed TRIGGER-AWARE: naive splitting on ";" cuts open
//    trigger bodies (BEGIN … END contains ';'), which both breaks trigger
//    creation and—after filtering out an FTS trigger's head—leaves orphaned
//    bare "END" statements (executes as COMMIT → "cannot commit - no
//    transaction is active").
// 2. `CREATE TABLE sqlite_sequence` is dropped — sqlite dumps include the
//    implicit AUTOINCREMENT bookkeeping table, but SQLite forbids creating it
//    by hand ("object name reserved for internal use").
// 3. Every CREATE gets IF NOT EXISTS — the bootstrap in src/db/connection.tsx
//    is gated on a sentinel table, so partially-bootstrapped DBs (crashes,
//    older bugs) re-run and converge instead of failing on "already exists".
//    Only affects brand-new local DBs (PLAN.md D2 — desktop owns migrations).
const fs = require("fs");
const sql = fs.readFileSync("src/db/schema.sql", "utf8");

// Parse into top-level statements. Split on ';' at line ends, then glue
// trigger bodies back together: a chunk that opens a CREATE TRIGGER is not
// complete until a chunk that is just END (optionally with whitespace).
const rawChunks = sql
  .split(/;\s*(?:\r?\n)/)
  .map((s) => s.trim())
  .filter((s) => s.length > 0);

const parsed = [];
for (let i = 0; i < rawChunks.length; i++) {
  let chunk = rawChunks[i];
  if (/^CREATE\s+TRIGGER\b/i.test(chunk)) {
    // consume pieces (incl. the closing bare END) into this statement
    while (i + 1 < rawChunks.length) {
      i++;
      chunk += ";\n" + rawChunks[i];
      if (/^\s*END\s*$/i.test(rawChunks[i])) break;
    }
  }
  parsed.push(chunk);
}

function sanitize(stmt) {
  if (/^CREATE\s+TABLE\s+(["'`]?)?sqlite_sequence\b/i.test(stmt)) return null;
  return stmt
    .replace(/^CREATE\s+VIRTUAL\s+TABLE\s+(?!IF\s+NOT\s+EXISTS)/i, "CREATE VIRTUAL TABLE IF NOT EXISTS ")
    .replace(/^CREATE\s+UNIQUE\s+INDEX\s+(?!IF\s+NOT\s+EXISTS)/i, "CREATE UNIQUE INDEX IF NOT EXISTS ")
    .replace(/^CREATE\s+TABLE\s+(?!IF\s+NOT\s+EXISTS)/i, "CREATE TABLE IF NOT EXISTS ")
    .replace(/^CREATE\s+INDEX\s+(?!IF\s+NOT\s+EXISTS)/i, "CREATE INDEX IF NOT EXISTS ")
    .replace(/^CREATE\s+TRIGGER\s+(?!IF\s+NOT\s+EXISTS)/i, "CREATE TRIGGER IF NOT EXISTS ");
}

const full = parsed.map(sanitize).filter(Boolean);

// Ordering fix: the desktop dump lists FTS *_data/_idx/… shadow tables BEFORE
// the CREATE VIRTUAL TABLE that owns them (organic sqlite_master order). But
// fts5 refuses CREATE VIRTUAL TABLE when its shadows already exist ("error
// creating shadow table …: table already exists"). Emit virtual tables first;
// triggers reference them — last.
const isVirtual = (s) => /^CREATE\s+VIRTUAL\s+TABLE/i.test(s);
const isFtsShadow = (s) =>
  /^CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?["'`]?(documents_fts|reading_articles_fts)_(data|idx|docsize|config)["'`]?/i.test(s);
const isTrigger = (s) => /^CREATE\s+TRIGGER/i.test(s);
// Split by construct role:
//  - SHADOWS dumped from sqlite_master must NOT be re-created on native: once
//    the owning virtual table exists, fts5 marks the names reserved and even
//    "CREATE TABLE IF NOT EXISTS 'documents_fts_data'" errors ("object name
//    reserved for internal use"). The module creates them itself.
//  - On web (no fts5 module): drop virtuals+triggers, KEEP shadow statements —
//    they're the only creators of those (plain) tables there and are harmless.
const plain = full.filter((s) => !isVirtual(s) && !isFtsShadow(s) && !isTrigger(s));
const orderedFull = [...plain, ...full.filter(isVirtual), ...full.filter(isTrigger)];
const web = [...plain, ...full.filter(isFtsShadow)];
const toScript = (stmts) => stmts.join(";\n") + ";\n";

// Also emit the parsed statements as arrays — bootstrap executes them one at
// a time. SQLite multi-statement exec silently ignores some construct classes
// in string form (observed: CREATE VIRTUAL TABLE swallowed inside a 100+
// statement script on some builds); per-statement execution gives exact
// per-statement errors instead.

fs.writeFileSync(
  "src/db/schema_sql.ts",
  "// GENERATED by scripts/gen-schema.js from schema.sql — do not edit.\n" +
    `const schema = ${JSON.stringify(toScript(orderedFull))};\n` +
    "export default schema;\n" +
    "/** Web variant: no FTS5 in expo-sqlite's web wa-sqlite build. */\n" +
    `export const schemaWeb = ${JSON.stringify(toScript(web))};\n` +
    `export const schemaStatements = ${JSON.stringify(orderedFull)};\n` +
    `export const schemaWebStatements = ${JSON.stringify(web)};\n`
);
console.log(
  `schema_sql.ts regenerated: ${orderedFull.length} native statements (shadow-table dump rows dropped — the fts5 module creates its own; virtual tables before triggers), ${web.length} web statements (no FTS5 in expo's web wa-sqlite build: virtuals+triggers dropped, shadows kept as plain tables). sqlite_sequence skipped, IF NOT EXISTS everywhere.`
);
