// scripts/gen-schema.js — regenerates src/db/schema_sql.ts from src/db/schema.sql
const fs = require("fs");
const sql = fs.readFileSync("src/db/schema.sql", "utf8");
fs.writeFileSync(
  "src/db/schema_sql.ts",
  `// GENERATED by scripts/gen-schema.js from schema.sql — do not edit.\nconst schema = ${JSON.stringify(sql)};\nexport default schema;\n`
);
