param(
    # Kept only for backward compatibility with the old documented flow;
    # electron-builder has no portable-zip target configured here anymore.
    [switch]$Portable
)

$ErrorActionPreference = "Stop"

if ($Portable) {
    Write-Warning "The -Portable zip flow was Tauri-era and is no longer wired up. Building the NSIS installer instead."
}

# LLVM/libclang is still required on Windows: the Rust sidecar's sherpa-onnx
# bindings are generated by bindgen during `cargo build` (bun run core:build
# inside package:win). Resolve it from scoop, which is how the old script
# located it too.
$llvmPrefix = (scoop prefix llvm) 2>$null
if ($llvmPrefix) {
    $env:LIBCLANG_PATH = Join-Path $llvmPrefix.Trim() "bin"
    $libclang = Join-Path $env:LIBCLANG_PATH "libclang.dll"
    if (-not (Test-Path -LiteralPath $libclang)) {
        throw "libclang.dll was not found at: $libclang — reinstall scoop's llvm package"
    }
} elseif (-not $env:LIBCLANG_PATH) {
    throw "LLVM is not installed. Run: scoop install llvm (or set LIBCLANG_PATH yourself)"
}

# The real build: Rust sidecar release binary, typecheck + Vite bundle, then
# electron-builder with this repo's electron-builder.yml (win target: NSIS
# x64). Artifacts land in ../dist-releases/, including latest.yml for the
# electron-updater feed published to GitHub Releases.
Push-Location $PSScriptRoot
try {
    bun run package:win
} finally {
    Pop-Location
}
