//! Shared ad/tracker-blocking engine for the Browser page.
//!
//! One implementation serves both hosts:
//!   - **Desktop**: the Electron main process intercepts requests with
//!     `session.webRequest.onBeforeRequest` (an Electron-only API the Rust
//!     sidecar can't reach) and asks this engine — running in the `tanwords`
//!     core sidecar over localhost — whether each subresource should be
//!     blocked. The matching logic is Rust, not a JS adblock library.
//!   - **Web**: the axum server runs this same engine as it proxies the
//!     iframe's page and subresources (see `web/server`).
//!
//! The engine is built from EasyList + EasyPrivacy plus uBlock Origin's own
//! lists (uBO's YouTube / anti-anti-adblock rules live there), and ships with
//! uBO's scriptlet + redirect **resource library** embedded at compile time
//! (`resources/ublock-resources.json`, generated by
//! `scripts/build-adblock-resources.mjs`). Scriptlet rules (`##+js(...)`) and
//! `$redirect` rules only work when those resources are loaded — without them
//! `injected_script` is empty and redirects never fire.
//!
//! Lists are fetched on first use and the compiled engine is cached to disk
//! (with a 24h TTL), so later launches work offline and stay fast. The build
//! is lazy and fallible: if the fetch fails (first run, offline), checks
//! allow everything — a missing blocker never breaks browsing. A stale cache
//! is used immediately and refreshed in the background.
//!
//! `adblock::Engine` is `!Send + !Sync` under the crate's default
//! `single-thread` feature (it owns `Rc`/`RefCell`), so it cannot be shared
//! across worker threads via an `Arc` or sent through a channel. Instead it
//! lives on one dedicated OS thread; other tasks talk to it through a
//! channel. A check is a single in-process hop plus a microsecond engine
//! match.

use std::sync::Arc;
use std::time::{Duration, SystemTime, UNIX_EPOCH};

use adblock::{
    lists::FilterSet,
    request::Request as AdRequest,
    Engine,
};
/// Re-exported for callers that need to parse/inspect the resource bundle.
pub use adblock::resources::Resource as AdblockResource;
use serde::Serialize;
use tokio::sync::{mpsc, oneshot, OnceCell};

/// How long a compiled-engine cache stays valid before a background refresh
/// is triggered. Rule lists change constantly (uBO's `quick-fixes.txt` is
/// updated within days of a YouTube change), so a permanent cache would mean
/// the list never actually refreshes.
const CACHE_TTL: Duration = Duration::from_secs(24 * 60 * 60);

/// Where on disk the serialized engine lives. Sits in the OS cache dir
/// alongside the rest of the app's caches.
fn cache_path() -> Option<std::path::PathBuf> {
    let dir = dirs::cache_dir()
        .or_else(dirs::data_dir)
        .unwrap_or_else(std::env::temp_dir);
    Some(dir.join("tanwords").join("adblock-engine.bin"))
}

/// Sidecar metadata for the engine cache: when it was built and which list
/// URLs went into it. When the URL set changes (a code change), the cache is
/// treated as stale regardless of age.
#[derive(Serialize, serde::Deserialize)]
struct CacheMeta {
    built_at: u64,
    urls_hash: String,
}

fn cache_meta_path() -> Option<std::path::PathBuf> {
    let dir = dirs::cache_dir()
        .or_else(dirs::data_dir)
        .unwrap_or_else(std::env::temp_dir);
    Some(dir.join("tanwords").join("adblock-engine.meta"))
}

fn list_urls_hash() -> String {
    let mut h = 0u64;
    for u in LIST_URLS {
        h = h.wrapping_mul(31).wrapping_add(u.as_bytes().iter().fold(0u64, |a, b| a.wrapping_mul(31).wrapping_add(*b as u64)));
    }
    format!("{h:x}")
}

/// The filter lists that make up the engine. EasyList/EasyPrivacy give the
/// general ad+tracker coverage; uBO's own lists add the rules EasyList can't
/// keep up with — notably YouTube's ad placements, which uBO tracks in
/// `filters.txt` and hot-fixes within days in `quick-fixes.txt`. All are
/// scriptlet-heavy, which is why the resource library (below) is mandatory.
const LIST_URLS: &[&str] = &[
    "https://easylist.to/easylist/easylist.txt",
    "https://easylist.to/easyprivacy/easyprivacy.txt",
    "https://ublockorigin.github.io/uAssetsCDN/filters/filters.min.txt",
    "https://ublockorigin.github.io/uAssetsCDN/filters/quick-fixes.min.txt",
    "https://ublockorigin.github.io/uAssetsCDN/filters/unbreak.min.txt",
    "https://ublockorigin.github.io/uAssetsCDN/filters/privacy.min.txt",
    "https://ublockorigin.github.io/uAssetsCDN/filters/badware.min.txt",
];

/// The uBO resource library (scriptlets + redirects), embedded at compile
/// time. Generated by `scripts/build-adblock-resources.mjs` from Ghostery's
/// pre-compiled uBO resources bundle — adblock-rust's own
/// `assemble_scriptlet_resources` is `#[deprecated]` and cannot parse uBO's
/// current ES-module scriptlet format, so we ship a converted bundle instead.
const EMBEDDED_RESOURCES: &str = include_str!("resources/ublock-resources.json");

/// Parse the embedded resource bundle into `Resource`s. On failure (a bad
/// bundle would be a build error in practice) log loudly and return empty —
/// the engine still works, only scriptlets/redirects are missing.
fn embedded_resources() -> Vec<AdblockResource> {
    match serde_json::from_str::<Vec<AdblockResource>>(EMBEDDED_RESOURCES) {
        Ok(r) => r,
        Err(e) => {
            eprintln!("[adblock] embedded resource bundle failed to parse: {e}");
            Vec::new()
        }
    }
}

/// What to do with a request the engine was asked about.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum BlockDecision {
    /// Let it through unchanged.
    Allow,
    /// Cancel the request (ad/tracker matched).
    Block,
    /// Redirect to this URL/`data:` instead. `redirect` filters replace the
    /// resource (e.g. an empty pixel for a tracked beacon).
    Redirect(String),
}

/// A message to the engine worker thread: a network check, a cosmetics
/// query, or a cache-reload signal, each with its reply slot where relevant.
enum WorkerMsg {
    Check {
        url: String,
        source: String,
        rtype: String,
        reply: oneshot::Sender<BlockDecision>,
    },
    Cosmetics {
        url: String,
        reply: oneshot::Sender<adblock::cosmetic_filter_cache::UrlSpecificResources>,
    },
    /// The background refresher finished writing a fresh engine cache; reload
    /// it from disk. The engine itself is `!Send` under `single-thread`, so
    /// the fresh value crosses the channel as a cache write + signal, and the
    /// worker rebuilds it on its own thread.
    ReloadCache,
}

/// Handle to the engine worker. Cheap to clone (the channel sender is shared);
/// every clone talks to the same single-threaded engine.
#[derive(Clone)]
pub struct AdblockEngine {
    tx: Arc<mpsc::UnboundedSender<WorkerMsg>>,
}

impl AdblockEngine {
    /// Decide what to do with one outgoing request.
    ///
    /// `source_url` is the page that triggered the request (the referer);
    /// `resource_type` is an ABP-style type token (`script`, `image`,
    /// `stylesheet`, `xhr`, `document`, `sub_frame`, `other`, …). The engine
    /// falls back to URL-based type guessing for `other`.
    ///
    /// Fails open: if the worker is unreachable or doesn't reply in time, the
    /// request is allowed — a blocker must never stall or blank a page.
    pub async fn check(&self, url: &str, source_url: &str, resource_type: &str) -> BlockDecision {
        let (reply_tx, reply_rx) = oneshot::channel();
        if self
            .tx
            .send(WorkerMsg::Check {
                url: url.to_string(),
                source: source_url.to_string(),
                rtype: resource_type.to_string(),
                reply: reply_tx,
            })
            .is_err()
        {
            return BlockDecision::Allow;
        }
        match tokio::time::timeout(Duration::from_millis(500), reply_rx).await {
            Ok(Ok(d)) => d,
            _ => BlockDecision::Allow,
        }
    }

    /// Query the engine's cosmetic filter cache for a URL. Returns hide
    /// selectors + (with the resource library loaded) injected scriptlets.
    /// Fails open with empty resources on timeout/worker-down.
    pub async fn url_cosmetic_resources(&self, url: &str) -> adblock::cosmetic_filter_cache::UrlSpecificResources {
        let (reply_tx, reply_rx) = oneshot::channel();
        if self
            .tx
            .send(WorkerMsg::Cosmetics {
                url: url.to_string(),
                reply: reply_tx,
            })
            .is_err()
        {
            return adblock::cosmetic_filter_cache::UrlSpecificResources::empty();
        }
        match tokio::time::timeout(Duration::from_millis(500), reply_rx).await {
            Ok(Ok(r)) => r,
            _ => adblock::cosmetic_filter_cache::UrlSpecificResources::empty(),
        }
    }
}

/// Global, lazily-initialized handle to the worker thread.
static ENGINE: OnceCell<AdblockEngine> = OnceCell::const_new();

/// Returns a handle to the shared engine, spawning the worker on first call.
/// The worker loads the cache (or builds the engine in the background) and
/// answers `Allow` for everything until it's ready, so no page load is ever
/// blocked behind the list fetch.
pub async fn engine() -> AdblockEngine {
    ENGINE
        .get_or_init(|| async {
            let (tx, rx) = mpsc::unbounded_channel::<WorkerMsg>();
            // A second handle to the same channel for the background refresher
            // thread (the worker itself is handed its half of this pair).
            let refresh_tx = tx.clone();
            std::thread::Builder::new()
                .name("tanwords-adblock".into())
                .spawn(move || engine_worker(rx, refresh_tx))
                .expect("spawn adblock engine worker");
            AdblockEngine { tx: Arc::new(tx) }
        })
        .await
        .clone()
}

/// The worker thread: owns the `!Send` engine, never shares it. Runs a
/// current-thread tokio runtime so the list fetch can be async.
fn engine_worker(mut rx: mpsc::UnboundedReceiver<WorkerMsg>, refresh_tx: mpsc::UnboundedSender<WorkerMsg>) {
    let rt = match tokio::runtime::Builder::new_current_thread().enable_all().build() {
        Ok(rt) => rt,
        Err(_) => {
            drain_allow(&mut rx);
            return;
        }
    };
    rt.block_on(async move {
        // Serve from cache immediately (stale or not). With no cache at all
        // (first launch), wait a bounded time for the initial build so the
        // very first page is actually filtered — but never more than the
        // deadline: a blocker must not stall a page. A stale cache is
        // refreshed in the background instead.
        let (mut current, stale) = load_cached();
        if current.is_some() {
            if stale {
                spawn_refresh(refresh_tx.clone());
            }
        } else {
            match tokio::time::timeout(Duration::from_secs(10), fetch_and_build()).await {
                Ok(Some(engine)) => {
                    save_cache(&engine);
                    current = Some(engine);
                }
                _ => {
                    eprintln!("[adblock] cold-start build failed; serving allow-all");
                }
            }
        }
        while let Some(msg) = rx.recv().await {
            match msg {
                WorkerMsg::Check { url, source, rtype, reply } => {
                    let decision = match &current {
                        Some(e) => decide(e, &url, &source, &rtype),
                        None => BlockDecision::Allow,
                    };
                    let _ = reply.send(decision);
                }
                WorkerMsg::Cosmetics { url, reply } => {
                    let res = match &current {
                        Some(e) => e.url_cosmetic_resources(&url),
                        None => adblock::cosmetic_filter_cache::UrlSpecificResources::empty(),
                    };
                    let _ = reply.send(res);
                }
                WorkerMsg::ReloadCache => {
                    if let (Some(e), _) = load_cached() {
                        current = Some(e);
                    }
                }
            }
        }
    });
}

/// Kick off a background list fetch → engine build → cache write. Runs on a
/// separate OS thread (it may take tens of seconds on a cold network) and
/// never blocks the worker; when done it signals the worker to reload from
/// disk via the `ReloadCache` message.
fn spawn_refresh(refresh_tx: mpsc::UnboundedSender<WorkerMsg>) {
    std::thread::Builder::new()
        .name("tanwords-adblock-refresh".into())
        .spawn(move || {
            let rt = match tokio::runtime::Builder::new_current_thread().enable_all().build() {
                Ok(rt) => rt,
                Err(_) => return,
            };
            rt.block_on(async move {
                match fetch_and_build().await {
                    Some(engine) => {
                        save_cache(&engine);
                        let _ = refresh_tx.send(WorkerMsg::ReloadCache);
                    }
                    None => {
                        eprintln!("[adblock] background list refresh failed; keeping current engine");
                    }
                }
            });
        })
        .ok();
}

/// Drain a channel with `Allow`/empty — used only when the runtime itself
/// failed to build, which is effectively never.
fn drain_allow(rx: &mut mpsc::UnboundedReceiver<WorkerMsg>) {
    while let Ok(msg) = rx.try_recv() {
        match msg {
            WorkerMsg::Check { reply, .. } => { let _ = reply.send(BlockDecision::Allow); }
            WorkerMsg::Cosmetics { reply, .. } => { let _ = reply.send(adblock::cosmetic_filter_cache::UrlSpecificResources::empty()); }
            WorkerMsg::ReloadCache => {}
        }
    }
}

/// Map a caller's resource-type token onto the ABP spelling adblock-rust
/// understands.
///
/// **Load-bearing.** adblock-rust's `cpt_match_type` matches snake_case ABP
/// tokens and silently falls back to `Other` for anything else. Electron's
/// `webRequest` reports Chromium's camelCase spellings (`subFrame`,
/// `mainFrame`, `cspReport`, `webSocket`), so passing them through verbatim
/// typed every ad iframe as `Other` — `$subdocument` and `$websocket` rules
/// (a large slice of EasyList, and most of uBO's ad-frame rules) never
/// matched at all. The tokens that already agree (`script`, `image`,
/// `stylesheet`, `font`, `object`, `media`, `ping`, `xhr`, `other`) pass
/// through unchanged.
fn normalize_rtype(rtype: &str) -> &str {
    match rtype {
        "mainFrame" => "main_frame",
        "subFrame" => "sub_frame",
        "cspReport" => "csp_report",
        "webSocket" => "websocket",
        other => other,
    }
}

fn decide(engine: &Engine, url: &str, source: &str, rtype: &str) -> BlockDecision {
    let rtype = normalize_rtype(rtype);
    // Never block a top-level document load — that would blank the page.
    if rtype.eq_ignore_ascii_case("document")
        || rtype.eq_ignore_ascii_case("main_frame")
    {
        return BlockDecision::Allow;
    }
    // adblock 0.13 grew an HTTP-method argument (for `$method=` rules). The
    // browser never tells us one here, so "get" keeps the pre-0.13 behaviour
    // of matching every request as if it were a GET.
    let request = match AdRequest::new(url, source, rtype, "get") {
        Ok(r) => r,
        Err(_) => return BlockDecision::Allow,
    };
    let result = engine.check_network_request(&request);
    // 0.13 replaced the `matched` bool with `should_block()`, which folds in
    // matched exception rules — exactly the decision the caller needs.
    if result.should_block() {
        BlockDecision::Block
    } else if let Some(redirect) = result.redirect {
        BlockDecision::Redirect(redirect)
    } else {
        BlockDecision::Allow
    }
}

/// Build a fresh engine from the lists, attach the resource library, and
/// persist both to disk. Returns `None` if *every* list failed (a missing
/// single list is skipped with a log — the engine is still useful without
/// it).
async fn fetch_and_build() -> Option<Engine> {
    let client = reqwest::Client::builder()
        .gzip(true)
        .brotli(true)
        .timeout(Duration::from_secs(60))
        .build()
        .ok()?;

    let mut filter_set = FilterSet::new(false);
    let mut loaded_any = false;
    for url in LIST_URLS {
        match client.get(*url).send().await {
            Ok(resp) if resp.status().is_success() => match resp.text().await {
                Ok(text) => {
                    let _ = filter_set.add_filter_list(text, Default::default());
                    loaded_any = true;
                }
                Err(e) => eprintln!("[adblock] list {url} read failed: {e}"),
            },
            Ok(resp) => eprintln!("[adblock] list {url} returned {}", resp.status()),
            Err(e) => eprintln!("[adblock] list {url} fetch failed: {e}"),
        }
    }
    if !loaded_any {
        eprintln!("[adblock] all lists failed to load; engine unavailable");
        return None;
    }
    let engine = Engine::new_with_filter_set(filter_set);
    Some(with_resources(engine))
}

/// Attach the embedded uBO resource library to an engine. Without this,
/// scriptlet (`##+js(...)`) rules resolve to nothing and `$redirect` rules
/// never fire — both depend on named resources.
fn with_resources(mut engine: Engine) -> Engine {
    engine.use_resources(embedded_resources());
    engine
}

/// Load the compiled engine from disk, if present and loadable. Returns
/// `(engine, stale)` — `stale` means the cache is usable but old enough (or
/// built from a different list set) that a background refresh should run.
fn load_cached() -> (Option<Engine>, bool) {
    let path = match cache_path() {
        Some(p) => p,
        None => return (None, true),
    };
    let bytes = match std::fs::read(&path) {
        Ok(b) => b,
        Err(_) => return (None, true),
    };
    let mut engine = Engine::default();
    if engine.deserialize(&bytes).is_err() {
        return (None, true);
    }
    let engine = with_resources(engine);

    // Staleness: meta missing/parseable, older than TTL, or list set changed.
    let stale = match cache_meta_path().and_then(|p| std::fs::read_to_string(p).ok()) {
        Some(meta) => match serde_json::from_str::<CacheMeta>(&meta) {
            Ok(m) => {
                let now = SystemTime::now().duration_since(UNIX_EPOCH).map(|d| d.as_secs()).unwrap_or(0);
                m.urls_hash != list_urls_hash() || now.saturating_sub(m.built_at) >= CACHE_TTL.as_secs()
            }
            Err(_) => true,
        },
        None => true,
    };
    (Some(engine), stale)
}

/// Persist the compiled engine plus its build metadata.
fn save_cache(engine: &Engine) {
    let Some(path) = cache_path() else { return };
    let Some(dir) = path.parent() else { return };
    if std::fs::create_dir_all(dir).is_err() {
        return;
    }
    let _ = std::fs::write(&path, engine.serialize());
    let meta = CacheMeta {
        built_at: SystemTime::now().duration_since(UNIX_EPOCH).map(|d| d.as_secs()).unwrap_or(0),
        urls_hash: list_urls_hash(),
    };
    if let Some(meta_path) = cache_meta_path() {
        let _ = std::fs::write(meta_path, serde_json::to_string(&meta).unwrap_or_default());
    }
}

/// Cosmetic resources for a page: a CSS stylesheet and an injected script.
///
/// `stylesheet` is a **selector list only** — `sel1,sel2,…` — deliberately
/// *without* the `{display:none!important}` wrapper. Every injector (web
/// proxy, desktop preload) applies its own wrapper, so the value here must
/// stay naked or the CSS ends up double-wrapped and the trailing block is
/// invalid.
///
/// `script` is the engine's `injected_script`: the compiled uBO scriptlets
/// (e.g. `json-prune` on YouTube, `set-constant` on anti-adblock walls) that
/// the page's rules call for. Empty unless the resource library loaded.
#[derive(Serialize, Clone)]
pub struct CosmeticResources {
    #[serde(rename = "stylesheet")]
    pub stylesheet: String,
    #[serde(rename = "script")]
    pub script: String,
}

/// Returns the cosmetic resources (CSS selectors + injected script) for a
/// page URL. Both come from the engine: hide-selectors from EasyList/uBO
/// cosmetic rules, injected script from the uBO scriptlet library. No
/// hand-written scripts remain — YouTube handling follows the uBO lists.
pub async fn cosmetics_for(url: &str) -> CosmeticResources {
    let engine = engine().await;
    let res = engine.url_cosmetic_resources(url).await;
    CosmeticResources {
        stylesheet: res.hide_selectors.into_iter().collect::<Vec<_>>().join(","),
        script: res.injected_script,
    }
}

/// RPC result for `adblock_check` — what the desktop's Electron main process
/// asks the sidecar on every subresource request.
#[derive(Serialize)]
pub struct AdblockCheckResult {
    #[serde(rename = "block")]
    pub block: bool,
    #[serde(rename = "redirect")]
    pub redirect: Option<String>,
}

/// Decide what to do with one request, asked over the sidecar RPC by the
/// desktop Electron main's `session.webRequest.onBeforeRequest` handler. The
/// matching runs here, in the Rust core; Electron main only interprets the
/// answer. (On web the proxy calls `engine().check` in-process instead.)
#[crate::shim::command]
pub async fn adblock_check(
    url: String,
    source_url: String,
    resource_type: String,
) -> Result<AdblockCheckResult, String> {
    let engine = engine().await;
    Ok(match engine.check(&url, &source_url, &resource_type).await {
        BlockDecision::Allow => AdblockCheckResult { block: false, redirect: None },
        BlockDecision::Block => AdblockCheckResult { block: true, redirect: None },
        BlockDecision::Redirect(r) => AdblockCheckResult { block: false, redirect: Some(r) },
    })
}

/// RPC for `adblock_cosmetics` — returns the CSS + script to inject into a
/// page. Called by the desktop preload (via a sync IPC hop to main, which
/// fetches from the sidecar) and by the web proxy (in-process).
#[crate::shim::command]
pub async fn adblock_cosmetics(url: String) -> Result<CosmeticResources, String> {
    Ok(cosmetics_for(&url).await)
}
